name: CheckLinks

run-name: CheckLinks

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  checklinks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.2

      - name: Install Dependencies
        run: pip install -r /home/runner/work/GameWeb/GameWeb/.github/scripts/CheckLinks/dependencies.txt

      - name: Run Python Script
        run: python .github/scripts/CheckLinks/CheckLinks.py
